### ISSUE TITLE
how to incorporate not only wavform as input

### ISSUE THREAD

**Issue by gitgaviny** [TideDancer/interspeech21_emotion#13]
Dear @TideDancer ,

Thank you very much for providing the program of interspeech paper!

I'm a bignner of hugging face training api, and I find it difficult to control the input of the model. 
For example, if I want an additional branch of feature extractor with MFCC as input rather than raw wavform (or using mannual trasncription or video input as multimodal system), is that possible to train it together with this wav2vec2 model? 
Since the length of labels are consistant, we can simply use [:-1] or [:-2] to build multi-task learning model. 
But this is not applicable for varible length input features. 
Hope to get your reply.

**Comment by gitgaviny** [comment]
Or could you please tell me how to save features of the hidden states (like torchvision.models._utils.IntermediateLayerGetter did) so that I can use them as the input of another costum layer. Directly use torch.save can only processed batch to batch, is there any api can help me with that?
I tried to load the pre-trained model (pytorch_model.bin) to my own model and train without transformer.trainer, so that I can use costum input, but the model tend to classify all inputs (IEMOCAP using raw waveform) into one class. So I'm interested how to combine this model with my own dataset class.

**Comment by TideDancer** [comment]
Hello @gavinyuan1 , thanks for your interest.
1. Using other features like MFCC: I think the best way is to look at the Huggingface datasets package: https://huggingface.co/docs/datasets/audio_process, and https://huggingface.co/docs/datasets/process. The input data extractor and batch processor are defined there. You can build a customized one to process the data and feed into the model
2. Obtain intermediate layer's output / hidden features: As far as I know, the easiest way is to use pytorch hooks: https://pytorch.org/docs/stable/generated/torch.nn.modules.module.register_module_forward_hook.html. Basically you can define a forward_hook to extract any variable's values at run time. There are also tutorials like https://medium.com/analytics-vidhya/pytorch-hooks-5909c7636fb.
Hope these addresses your questions.

**Comment by gavinyuan1** [comment]
Thank you very much for the reply.
For the dataset class, I tried to create an "input_length" variable just like the tutorial did. I use:
for i in range(len(batch["input_values"])):
  batch["input_length"][i] = len(batch["input_values"][i])

But it shows:
  File "run_emotion.py", line 611, in <module>
    main()
  File "run_emotion.py", line 505, in main
    num_proc=data_args.preprocessing_num_workers,
  File "/n/work3/user/anaconda3/envs/is/lib/python3.7/site-packages/datasets/arrow_dataset.py", line 1289, in map
    update_data = does_function_return_dict(test_inputs, test_indices)
  File "/n/work3/user/anaconda3/envs/is/lib/python3.7/site-packages/datasets/arrow_dataset.py", line 1260, in does_function_return_dict
    function(*fn_args, indices, **fn_kwargs) if with_indices else function(*fn_args, **fn_kwargs)
  File "run_emotion.py", line 489, in prepare_dataset
    batch["input_length"][i] = len(batch["input_values"][i])
KeyError: 'input_length'

I can only create another keyword by getting the return value of processor, like:
batch["input_length"] = processor(batch["speech"], sampling_rate=batch["sampling_rate"][0]).input_values
Then I tried the tutorial again by:
batch["input_length"] = processor(batch["speech"], sampling_rate=batch["sampling_rate"][0]).input_values
for i in range(len(batch["input_values"])):
    batch["input_length"][i] = None
    batch["input_length"][i] = len(batch["input_values"][i])

And there's another problem:
Traceback (most recent call last):
  File "run_emotion.py", line 612, in <module>
    main()
  File "run_emotion.py", line 506, in main
    num_proc=data_args.preprocessing_num_workers,
  File "/n/work3/user/anaconda3/envs/is/lib/python3.7/site-packages/datasets/arrow_dataset.py", line 1369, in map
    result = concatenate_datasets(transformed_shards)
  File "/n/work3/user/anaconda3/envs/is/lib/python3.7/site-packages/datasets/arrow_dataset.py", line 2666, in concatenate_datasets
    raise ValueError("Features must match for all datasets")
ValueError: Features must match for all datasets

This makes me confused about this class, because I can't even find the difference in my code with the tutorial.

And I find in the DataCollatorCTCWithPadding, the input features can only capture "input_values" and "labels".
Because even when I change the input_values into another name like:
batch["input_values"] = processor(batch["speech"], sampling_rate=batch["sampling_rate"][0]).input_values ->
batch["input"] = processor(batch["speech"], sampling_rate=batch["sampling_rate"][0]).input_values

In DataCollatorCTCWithPadding, the keys of features have only "labels", without "input".
So I'm frustrated about this trainer thing, and I can not find any example using keywords other than "input_values" and "labels".
So I'm thinking if I missed something in DataCollatorCTCWithPadding or trainer.
Hope to get your reply for this problem!

**Comment by gitgaviny** [comment]
Thank you for your reply! I will close this issue.
