### ISSUE TITLE
Testing model, inference

### ISSUE THREAD

**Issue by 2Bye** [TideDancer/interspeech21_emotion#6]
Hello, thanks for your work.
I trained the model , but I couldn't write code for testing. Maybe you have a ready recipe for inference?

**Comment by TideDancer** [comment]
Hello, thank you for your interest. I have added a script for inference, prediction.sh. You can run "bash prediction.sh [path/to/the/saved/model]". Let me know if that works. Thanks!

**Comment by 2Bye** [comment]
@TideDancer 
Thanks, I'll try this. I will write feedback later

I also have a question about your future work. As I understand it, the goal of the work was to train the model to recognize emotions, while you left the previous mechanism for the task of speech recognition. Are there any plans to remove this feature in the future?
I believe that this will reduce the training time and allow more flexibility in setting up the model.

**Comment by TideDancer** [comment]
This is a good point. Since the ASR part is a big booster to improve the emotion results, it is tricky to remove this part. My future work indeed includes extending the framework with other tasks and modality. I wish to find some way, to remove the ASR, but with other helpers in emotion recognition, e.g. videos. Any suggestions / comments are welcome!
